# Generated by Django 5.2.7 on 2026-09-19 19:52

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("directory", "0003_recommendationrequest_email_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(blank=True, max_length=40)),
                (
                    "message",
                    models.TextField(
                        blank=True,
                        help_text="What the patient wants help with, in their words.",
                    ),
                ),
                (
                    "share_concerns",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the patient agreed to share their selected concerns.",
                    ),
                ),
                (
                    "consent_text",
                    models.TextField(
                        help_text="The exact wording the patient agreed to, stored verbatim."
                    ),
                ),
                (
                    "consented_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("ip_hash", models.CharField(blank=True, db_index=True, max_length=64)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("viewed", "Viewed"),
                            ("responded", "Responded"),
                            ("closed", "Closed"),
                        ],
                        default="new",
                        max_length=10,
                    ),
                ),
                ("first_viewed_at", models.DateTimeField(blank=True, null=True)),
                ("responded_at", models.DateTimeField(blank=True, null=True)),
                ("practitioner_note", models.TextField(blank=True)),
                (
                    "patient",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="contact_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "practitioner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contact_requests",
                        to="directory.practitioner",
                    ),
                ),
                (
                    "recommendation_request",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="contact_requests",
                        to="directory.recommendationrequest",
                    ),
                ),
            ],
            options={
                "verbose_name": "contact request",
                "verbose_name_plural": "contact requests",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="ContactRequestAccess",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip_hash", models.CharField(blank=True, max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "contact_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="accesses",
                        to="outreach.contactrequest",
                    ),
                ),
            ],
            options={
                "verbose_name": "contact request access",
                "verbose_name_plural": "contact request accesses",
                "ordering": ("-created_at",),
            },
        ),
        migrations.AddIndex(
            model_name="contactrequest",
            index=models.Index(
                fields=["practitioner", "status", "created_at"],
                name="outreach_co_practit_1c0a42_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="contactrequest",
            index=models.Index(
                fields=["created_at"], name="outreach_co_created_321b7b_idx"
            ),
        ),
    ]
