# Generated by Django 5.2.7 on 2026-09-19 13:33

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Modality",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=120, unique=True)),
                ("slug", models.SlugField(blank=True, max_length=140, unique=True)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                "verbose_name_plural": "modalities",
                "ordering": ("sort_order", "name"),
            },
        ),
        migrations.CreateModel(
            name="HealthConcern",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=120, unique=True)),
                ("slug", models.SlugField(blank=True, max_length=140, unique=True)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
                (
                    "modalities",
                    models.ManyToManyField(
                        blank=True, related_name="concerns", to="directory.modality"
                    ),
                ),
            ],
            options={
                "ordering": ("sort_order", "name"),
            },
        ),
        migrations.CreateModel(
            name="Practitioner",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("display_name", models.CharField(max_length=200)),
                (
                    "credentials",
                    models.CharField(
                        blank=True, help_text="e.g. LAc, ND, DC, MD", max_length=120
                    ),
                ),
                ("practice_name", models.CharField(blank=True, max_length=200)),
                ("bio", models.TextField(blank=True)),
                ("photo_url", models.URLField(blank=True)),
                ("website", models.URLField(blank=True)),
                ("phone", models.CharField(blank=True, max_length=40)),
                ("email", models.EmailField(blank=True, max_length=254)),
                (
                    "years_experience",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("address_line1", models.CharField(blank=True, max_length=200)),
                ("address_line2", models.CharField(blank=True, max_length=200)),
                ("city", models.CharField(blank=True, max_length=120)),
                (
                    "region",
                    models.CharField(
                        blank=True, help_text="State/province", max_length=120
                    ),
                ),
                ("postal_code", models.CharField(blank=True, max_length=20)),
                ("country", models.CharField(default="US", max_length=2)),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=9,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(-90),
                            django.core.validators.MaxValueValidator(90),
                        ],
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=9,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(-180),
                            django.core.validators.MaxValueValidator(180),
                        ],
                    ),
                ),
                ("offers_telehealth", models.BooleanField(default=False)),
                ("accepting_new_patients", models.BooleanField(default=True)),
                ("accepts_insurance", models.BooleanField(default=False)),
                (
                    "tier",
                    models.CharField(
                        choices=[
                            ("standard", "Standard"),
                            ("verified", "Verified"),
                            ("partner", "Partner"),
                        ],
                        default="standard",
                        max_length=10,
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        default=False,
                        help_text="Only published practitioners can be recommended.",
                    ),
                ),
                (
                    "concerns",
                    models.ManyToManyField(
                        blank=True,
                        related_name="practitioners",
                        to="directory.healthconcern",
                    ),
                ),
                (
                    "modalities",
                    models.ManyToManyField(
                        blank=True,
                        related_name="practitioners",
                        to="directory.modality",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="practitioner",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("display_name",),
            },
        ),
        migrations.CreateModel(
            name="RecommendationRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "claim_token",
                    models.CharField(blank=True, db_index=True, max_length=64),
                ),
                ("location_label", models.CharField(blank=True, max_length=255)),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                ("radius_km", models.PositiveSmallIntegerField(default=40)),
                ("include_telehealth", models.BooleanField(default=True)),
                ("accepting_new_patients_only", models.BooleanField(default=False)),
                (
                    "concerns",
                    models.ManyToManyField(blank=True, to="directory.healthconcern"),
                ),
                (
                    "modalities",
                    models.ManyToManyField(blank=True, to="directory.modality"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recommendation_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Recommendation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("rank", models.PositiveSmallIntegerField()),
                ("score", models.FloatField()),
                ("distance_km", models.FloatField(blank=True, null=True)),
                ("reasons", models.JSONField(blank=True, default=list)),
                (
                    "practitioner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recommendations",
                        to="directory.practitioner",
                    ),
                ),
                (
                    "request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recommendations",
                        to="directory.recommendationrequest",
                    ),
                ),
            ],
            options={
                "ordering": ("rank",),
            },
        ),
        migrations.AddIndex(
            model_name="practitioner",
            index=models.Index(
                fields=["is_published", "tier"], name="directory_p_is_publ_448da5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="practitioner",
            index=models.Index(
                fields=["latitude", "longitude"], name="directory_p_latitud_7578ea_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="recommendation",
            constraint=models.UniqueConstraint(
                fields=("request", "practitioner"),
                name="unique_practitioner_per_request",
            ),
        ),
    ]
