# Generated by Django 5.2.7 on 2026-09-19 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("directory", "0002_distances_in_miles"),
    ]

    operations = [
        migrations.AddField(
            model_name="recommendationrequest",
            name="email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name="recommendationrequest",
            name="ip_hash",
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name="recommendationrequest",
            name="result_count",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="recommendationrequest",
            name="user_agent",
            field=models.CharField(blank=True, max_length=400),
        ),
    ]
