# Generated by Django 5.2.7 on 2026-09-19 15:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("directory", "0003_recommendationrequest_email_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyStat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("day", models.DateField(unique=True)),
                ("searches", models.PositiveIntegerField(default=0)),
                (
                    "zero_result_searches",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Searches that matched nobody — your coverage gaps.",
                    ),
                ),
                ("unique_visitors", models.PositiveIntegerField(default=0)),
                ("emails_captured", models.PositiveIntegerField(default=0)),
                ("recommendations_served", models.PositiveIntegerField(default=0)),
                ("practitioner_impressions", models.PositiveIntegerField(default=0)),
                ("practitioner_clicks", models.PositiveIntegerField(default=0)),
                (
                    "blocked_requests",
                    models.PositiveIntegerField(
                        default=0, help_text="Searches refused by the rate limit."
                    ),
                ),
                ("computed_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "daily usage",
                "verbose_name_plural": "daily usage",
                "ordering": ("-day",),
            },
        ),
        migrations.CreateModel(
            name="SearchQuota",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip_hash", models.CharField(db_index=True, max_length=64)),
                ("day", models.DateField(db_index=True)),
                ("search_count", models.PositiveIntegerField(default=0)),
                ("gave_email", models.BooleanField(default=False)),
                ("blocked_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "search quota",
                "verbose_name_plural": "search quotas",
                "ordering": ("-day",),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("ip_hash", "day"), name="unique_quota_per_day"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="PractitionerEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("impression", "Recommended"),
                            ("profile", "Profile opened"),
                            ("phone", "Phone revealed"),
                            ("website", "Website opened"),
                        ],
                        db_index=True,
                        max_length=12,
                    ),
                ),
                ("tier_at_event", models.CharField(blank=True, max_length=10)),
                (
                    "practitioner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="directory.practitioner",
                    ),
                ),
                (
                    "request",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="practitioner_events",
                        to="directory.recommendationrequest",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "indexes": [
                    models.Index(
                        fields=["practitioner", "kind", "created_at"],
                        name="analytics_p_practit_3e2c07_idx",
                    ),
                    models.Index(
                        fields=["created_at"], name="analytics_p_created_a7acb4_idx"
                    ),
                ],
            },
        ),
    ]
