# Generated by Django 5.2.7 on 2026-09-19 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="searchquota",
            name="contact_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
